### PR TITLE
Added UMD support

### PR DESCRIPTION
**Pull request by lagden**
I used [this](https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js) for tap.js and [this](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js) for jquery.tap.js

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks for the PR!

Instead of just adding AMD, could you reuse the UMD pattern here? https://github.com/alexgibson/shake.js

**Comment by lagden** [comment]
Interesting...
Sure!! I will update...

**Comment by lagden** [comment]
Done!

**Comment by alexgibson** [comment]
Thanks @lagden! Squashed and merged your commits in 67da85fa4bf0a61fa5fc39d3ad98b00b4719bc5a

**Pull request closed without merging**
